const A=[
{id:"vega",n:"Cmdr. Ilsa Vega",r:"Commander",tr:"Calm, decisive, methodical",sk:["Crew leadership","Systems oversight"],sl:[22,6],diet:"Omnivore",hr:[62,63,64,62,65,63,64],rh:56,rr:14,sp:98,bp:"118/76",rep:[6.5,3],feel:"Rested",app:"Normal",hyd:"Good",sw:3,st:2,fat:2,mood:"Steady",act:["Crew briefing","Treadmill 40 min","Log review"],sore:"None reported",ev:3,intol:[]},
{id:"okoye",n:"Maj. Tunde Okoye",r:"Pilot",tr:"Focused, dry humour",sk:["Rendezvous","Robotic arm"],sl:[23,6.5],diet:"Omnivore",hr:[68,70,69,72,71,70,73],rh:58,rr:15,sp:97,bp:"122/78",rep:[5.5,5],feel:"Tired",app:"Reduced",hyd:"Fair",sw:3,st:3,fat:4,mood:"Flat",act:["Robotic arm drill","Resistance 30 min","Maintenance"],sore:"Lower back, mild",ev:1,intol:[]},
{id:"lind",n:"Dr. Maja Lindqvist",r:"Flight Engineer",tr:"Curious, precise, quiet",sk:["Life support repair","Electronics"],sl:[22.5,6.5],diet:"Vegetarian",hr:[60,61,60,62,61,60,61],rh:54,rr:13,sp:99,bp:"112/72",rep:[7,2],feel:"Rested",app:"Normal",hyd:"Good",sw:2,st:2,fat:2,mood:"Positive",act:["Filter swap","Cycle ergometer 45 min","Inspection"],sore:"None reported",ev:2,intol:["meat"]},
{id:"patel",n:"Dr. Arjun Patel",r:"Science Researcher",tr:"Enthusiastic, talkative",sk:["Biology experiments","Data analysis"],sl:[0,7.5],diet:"Lactose intolerant",hr:[66,65,67,66,68,67,66],rh:57,rr:14,sp:98,bp:"120/77",rep:[7,2],feel:"Alert",app:"Normal",hyd:"Good",sw:3,st:2,fat:2,mood:"Positive",act:["Plant growth run","Resistance 30 min","Sample prep"],sore:"Neck, mild",ev:1,intol:["dairy"]},
{id:"mori",n:"Capt. Sora Mori",r:"EVA Specialist",tr:"Resilient, competitive",sk:["Spacewalks","Suit systems"],sl:[22,6],diet:"Omnivore, high energy",hr:[64,66,65,67,66,68,67],rh:52,rr:13,sp:98,bp:"116/74",rep:[6,4],feel:"Slightly tired",app:"Normal",hyd:"Fair",sw:3,st:3,fat:3,mood:"Focused",act:["Suit fit check","Treadmill 50 min","Tool inventory"],sore:"Shoulders, moderate",ev:6,intol:[]}];
const F=[
{n:"Rehydratable scrambled eggs",c:"Protein",k:190,p:12,fe:"data unavailable",t:"ingredients not verified",tg:[]},
{n:"Thermostabilized beef tips",c:"Protein",k:170,p:20,fe:"data unavailable",t:"meat",tg:["meat"],alt:2},
{n:"Rehydratable lentil soup",c:"Protein",k:140,p:9,fe:"data unavailable",t:"vegetarian",tg:[]},
{n:"Tortillas",c:"Grains",k:150,p:4,fe:"data unavailable",t:"vegan",tg:[]},
{n:"Rehydratable macaroni and cheese",c:"Grains",k:260,p:11,fe:"data unavailable",t:"contains dairy (assumed)",tg:["dairy"],alt:2},
{n:"Dried apricots",c:"Fruit",k:80,p:1,fe:"data unavailable",t:"snack",tg:[]},
{n:"Almonds",c:"Snacks",k:160,p:6,fe:"data unavailable",t:"snack, nut",tg:[]}];
let cur=A[0],view="sum",envm="cabin",cat="All",meal={};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const PC=[["#c98d6b","#2b1d16","#4fd8ff"],["#7a4a35","#111","#ffb84d"],["#f0c9a8","#d9b45a","#8b7bff"],["#a86f4c","#1a1a22","#4fd8ff"],["#e3b48c","#0e0e14","#ff6b6b"]];
function pt(a,s){const[k,hr,c]=PC[A.indexOf(a)];return `<svg class="pt" width="${s||56}" height="${s||56}" viewBox="0 0 64 64" role="img" aria-label="Illustrated portrait of ${a.n} (fictional)"><circle cx="32" cy="32" r="31" fill="#0b1226" stroke="${c}"/><path d="M12 60c2-14 12-18 20-18s18 4 20 18z" fill="#dfe8f7"/><rect x="26" y="52" width="12" height="6" rx="2" fill="${c}"/><circle cx="32" cy="29" r="13" fill="${k}"/><path d="M19 28c0-12 7-16 13-16s13 4 13 16c-3-5-8-7-13-7s-10 2-13 7z" fill="${hr}"/><circle cx="27" cy="31" r="1.6" fill="#111"/><circle cx="37" cy="31" r="1.6" fill="#111"/><path d="M28 37q4 3 8 0" stroke="#111" fill="none"/><circle cx="32" cy="29" r="15.5" fill="none" stroke="${c}" stroke-width="2" opacity=".7"/></svg>`}
const lv=x=>x<=2?"Low":x==3?"Moderate":"Elevated";
function card(t,v,u,x,st){return `<div class="card"><h3>${t}</h3><div class="big">${v} <span class="u">${u}</span></div><div class="u">${x}</div>${st?`<div class="st ${st[0]}">${st[1]}</div>`:""}</div>`}
function render(){const a=cur;
$("#ovgrid").innerHTML=card("Selected astronaut",a.n,"",a.r+" · "+a.diet,["ok","Information available"])+card("Fatigue (self-reported)",lv(a.fat),"","Reported sleep "+a.rep[0]+" h",a.rep[0]<6?["rv","Review required"]:["ok","Information available"])+card("Spacewalk experience",a.ev,"EVAs","Fictional history",["ok","Fictional"])+card("Outstanding checks",assessList().filter(i=>i[0]!="ok").length,"items","See Mission Planner",["rv","Review required"]);
$("#crew").innerHTML=A.map(x=>`<button class="card ${x.id==a.id?"on":""}" style="text-align:left" data-id="${x.id}" aria-pressed="${x.id==a.id}">${pt(x)}<b>${x.n}</b><div>${x.r}</div><div class="u">${x.tr}</div></button>`).join("");
$("#prof").innerHTML=`<span class="tag">Fictional profile</span><span class="tag f">AI-style vector portrait</span><br>${pt(a,72)}<h3 style="display:inline">${a.n}, ${a.r}</h3><p>${a.tr}. Skills: ${a.sk.join(", ")}.</p><p>Planned sleep: ${a.sl[0]}:00 for ${a.sl[1]} h. Diet: ${a.diet}. Recent: ${a.act.join(" → ")}. Soreness: ${a.sore}.</p>`;
const rg={hr:"Ordinary adult resting range: about 60–100 bpm (general reference)",rr:"Ordinary adult range: about 12–20 breaths/min (general reference)",sp:"Ordinary reference: roughly 95% or higher at rest (general reference)",bp:"Ordinary reference: about 120/80 mmHg or below (general reference)"};
const ex=view=="det";
$("#vitals").innerHTML=card("Heart rate",a.hr[6],"bpm","Resting: "+a.rh+" bpm"+(ex?". "+rg.hr:""),["ok","Simulated"])+card("Respiratory rate",a.rr,"/min",ex?rg.rr:"Simulated",["ok","Simulated"])+card("SpO2",a.sp,"%",ex?rg.sp:"Simulated",["ok","Simulated"])+card("Blood pressure",a.bp,"mmHg",ex?rg.bp:"Simulated",["ok","Simulated"]);
const h=a.hr,mn=Math.min(...h)-3,mx=Math.max(...h)+3;const pts=h.map((v,i)=>[40+i*85,130-(v-mn)/(mx-mn)*110]);
$("#hrchart").innerHTML=`<svg viewBox="0 0 600 150" width="100%" role="img" aria-label="Heart rate trend">${pts.map((p,i)=>`<text x="${p[0]-10}" y="148">D${i+1}</text>`).join("")}<polyline fill="none" stroke="#4fd8ff" stroke-width="2" points="${pts.map(p=>p.join(",")).join(" ")}"/>${pts.map((p,i)=>`<circle tabindex="0" role="button" aria-label="Day ${i+1} heart rate, select to read" r="9" cx="${p[0]}" cy="${p[1]}" fill="#4fd8ff" data-i="${i}" style="cursor:pointer"/>`).join("")}</svg>`;
const s0=a.sl[0],sd=a.rep[0],pl=a.sl[1];const seg=(st,d,c)=>{const l=(st%24)/24*100,w=d/24*100,pc=(x,y)=>`<i style="position:absolute;left:${x}%;width:${y}%;height:100%;background:${c};opacity:.85"></i>`;return pc(l,Math.min(w,100-l))+(l+w>100?pc(0,l+w-100):"")};
$("#sleep").innerHTML=`<div class="bar" style="position:relative;height:18px">${seg(s0,pl,"#8b7bff")}</div><div class="u">Planned: ${pl} h from ${s0}:00 (0–24 h bar)</div><div class="bar" style="position:relative;height:18px;margin-top:8px">${seg(s0,sd,"#4fd8ff")}</div><div class="u">Reported: ${sd} h, ${a.rep[1]} interruptions. Feels: ${a.feel}. Self-reported.</div>`;
$("#well").innerHTML=card("Appetite",a.app,"","Self-reported")+card("Hydration",a.hyd,"","Self-reported, not a diagnosis")+card("Stress / Fatigue",lv(a.st)+" / "+lv(a.fat),"","Self-reported scale 1–5")+card("Mood · Soreness",a.mood,"",a.sore);
envr();nut();assess();cmpr()}
const R=[["Space suit overview presentation","NASA Johnson Space Center (via NTRS 20170004971)","2017 (per NTRS record; unconfirmed)","https://ntrs.nasa.gov/api/citations/20170004971/downloads/20170004971.pdf"],["Extravehicular Activity Systems (EMU description, 29.6 kPa 100% O2, LCVG)","National Research Council / National Academies Press","undated in retrieved text","https://www.nap.edu/read/5826/chapter/6"],["Space shuttle and ISS EVA operations, ch. 5.4 (prebreathe protocols)","Gernhardt, NASA","2013","https://nasa.gov/wp-content/uploads/2023/03/gernhardt-eva-ops-chp-5.4-2013.pdf"],["NASA-STD-3001 Technical Brief: ECLSS, human-centered approach","NASA Office of the Chief Health and Medical Officer","2023","https://www.nasa.gov/wp-content/uploads/2023/07/eclss-technical-brief-ochmo.pdf"],["NASA's Exploration Atmospheres Working Group (cites ISS 14.7 psia, 21% O2)","Norcross et al., Aerospace Medicine and Human Performance 89(9):792","2018","https://asma.kglmeridian.com/downloadpdf/view/journals/amhp/89/9/article-p792.pdf"],["Life Support Systems: EVA (secondary: educational page, originally NASA Ames; EVA design duration, EMU functions)","NASA Ames education page, now hosted by NSS","undated","https://nss.org/settlement/nasa/teacher/course/eva.html"],["USDA FoodData Central (recommended source for nutrient data; NO values here were taken from it)","USDA Agricultural Research Service","n/a","https://fdc.nal.usda.gov/"]];
const cite=s=>s&&s.length?"<sup>"+s.map(n=>`<a href="#ref${n}">[${n}]</a>`).join("")+"</sup>":"";
function refInit(){$("#refs").innerHTML=R.map((r,i)=>`<li id="ref${i+1}">${r[0]}. ${r[1]}, ${r[2]}. <a href="${r[3]}" rel="noopener">${r[3]}</a></li>`).join("")}
const ENV={cabin:[["Cabin pressure","101.3 kPa (14.7 psi)","Published (ISS nominal)","Sea-level pressure. The suit runs at far lower pressure, which is why EVA preparation includes oxygen prebreathe.",[5]],["Oxygen","≈21 %","Published (ISS nominal)","Air-like oxygen fraction in the station cabin.",[5]],["CO2","Data unavailable","Limits exist in NASA-STD-3001 Vol 2; values not verified here","The environmental control system removes CO2. The limit depends on exposure duration and must be taken from the standard.",[4]],["Temperature","≈22 °C","Illustrative","Cabin thermal comfort value is a prototype assumption.",[]],["Humidity","≈45 %","Illustrative","Prototype assumption.",[]],["Ventilation","Nominal (simulated)","Simulated","Ventilation direction matters in microgravity because CO2-rich air can pool near the crew.",[]],["Radiation","Data unavailable","Source needed","Dose depends on orbit and solar activity.",[]],["Noise","Data unavailable","Source needed","Not sourced in this prototype.",[]],["Water / air supply","82 % / 78 % (simulated)","Simulated","Consumables bar is a demo, not station data.",[]]],
suit:[["Suit pressure","29.6 kPa (4.3 psi)","Published (EMU)","Deliberately low for mobility; differs from cabin pressure.",[1,2]],["Oxygen","100 % O2 at 29.6 kPa","Published (EMU)","The PLSS maintains this environment and makes up leakage and metabolic use.",[2]],["Oxygen supply level","74 % (simulated)","Simulated","Demo level only.",[]],["CO2 removal","Controlled by the PLSS","Published (function only)","Suit CO2 is removed by suit hardware, not by the cabin system. No CO2 level is sourced here.",[6]],["Thermal regulation","Water-cooled garment (LCVG)","Published (EMU)","Circulating water absorbs body heat and the PLSS rejects it. Temperature values are not sourced.",[2]],["Ventilation","Gas flow over the face and through garment tubing","Published (function only)","Ventilation gas is circulated by the PLSS.",[2,6]],["EVA design duration","Up to 8 h (ISS-era design target)","Published (secondary source)","Educational page states the target; actual operational limits may differ.",[6]],["Humidity","Data unavailable","Source needed","The EMU controls humidity (ref 6); no level is sourced.",[6]],["Radiation / dust","Data unavailable","Source needed","Outside the cabin, shelter is limited. Dust applies to surface missions only.",[]],["Water / consumables","70 % (simulated)","Simulated","Demo level only.",[]]]};
const tg=b=>/^Published/.test(b)?"Published spec":/^Simulated/.test(b)?"Simulated":/^Illustrative/.test(b)?"Illustrative":"Source needed";
function envr(){const L=ENV[envm];$("#suitdiag").hidden=envm!="suit";$("#env").innerHTML=L.map((e,i)=>`<button class="card" style="text-align:left" data-e="${i}"><h3>${e[0]}</h3><div class="big" style="font-size:1.15rem">${e[1]}</div><span class="st ${e[1].startsWith("Data")?"na":"ok"}">${e[1].startsWith("Data")?"Data unavailable":"Information available"}</span> <span class="tag f">${tg(e[2])}</span>${cite(e[4])}</button>`).join("")}
const SP=[["Helmet and visor","Part of the pressure garment. Ventilation gas flows over the face.",[6]],["Hard upper torso and controls","Torso shell. The life support system provides caution and warning and communications.",[2]],["Portable Life Support System (PLSS)","Backpack. Maintains 29.6 kPa, 100% oxygen; makes up leakage; circulates ventilation gas and cooling water; supplies power and communications.",[2]],["Liquid Cooling and Ventilation Garment","Worn under the pressure layer. Water in tubing absorbs body heat, rejected by the PLSS.",[2]],["Gloves","Pressure bladder, restraint layer and thermal micrometeoroid garment outer layer.",[2]],["Lower torso","Low suit pressure aids mobility but means prebreathe is needed before EVA.",[2,3]]];
function suitInit(){const S=[["rect",'x="92" y="86" width="116" height="104" rx="10"',2],["rect",'x="108" y="84" width="84" height="78" rx="16"',1],["circle",'cx="150" cy="48" r="34"',0],["rect",'x="112" y="166" width="76" height="150" rx="14"',5],["circle",'cx="62" cy="176" r="18"',4],["circle",'cx="238" cy="176" r="18"',4],["path",'d="M108 100L70 160M192 100L230 160M130 170V310M170 170V310" stroke-dasharray="6 4" stroke-width="3"',3]];
$("#suitsvg").innerHTML=`<svg viewBox="0 0 300 340" width="100%" style="max-width:340px" role="group" aria-label="Spacesuit schematic">${S.map(s=>`<${s[0]} class="part${s[2]==3?" lc":""}" data-p="${s[2]}" tabindex="0" role="button" aria-label="${SP[s[2]][0]}" ${s[1]}/>`).join("")}<text x="150" y="52">Helmet</text><text x="150" y="128">HUT</text><text x="236" y="112">PLSS</text><text x="62" y="212">Gloves</text><text x="150" y="250">Lower torso</text><text x="62" y="110">LCVG</text></svg>`;
document.addEventListener("keydown",e=>{const t=e.target;if((e.key=="Enter"||e.key==" ")&&t&&t.dataset){if(t.dataset.p!=null){e.preventDefault();suitSel(+t.dataset.p)}else if(t.dataset.i!=null){e.preventDefault();t.dispatchEvent(new MouseEvent("click",{bubbles:true}))}}})}
function suitSel(i){$$("#suitsvg .part").forEach(g=>g.classList.toggle("on",+g.dataset.p==i));$("#suitx").innerHTML=`<h3>${SP[i][0]}</h3><p>${SP[i][1]} ${cite(SP[i][2])}</p><p class="u">Schematic is simplified and not to scale. Component descriptions are published facts; the diagram itself is illustrative.</p>`}
function cmpInit(){$("#cmp").innerHTML=A.map(a=>`<option value="${a.id}">${a.n}</option>`).join("");$("#cmp").value=A[1].id;$("#cmp").onchange=cmpr}
function cmpr(){if($("#cmp").value==cur.id)$("#cmp").value=A[(A.indexOf(cur)+1)%A.length].id;const b=A.find(a=>a.id==$("#cmp").value),a=cur;
const rows=[["Role",x=>x.r],["Traits",x=>x.tr],["Skills",x=>x.sk.join(", ")],["Diet",x=>x.diet],["Reported sleep",x=>x.rep[0]+" h, "+x.rep[1]+" interruptions"],["Fatigue / stress",x=>lv(x.fat)+" / "+lv(x.st)],["Hydration",x=>x.hyd],["Soreness",x=>x.sore],["EVAs (fictional)",x=>x.ev]];
$("#cmpt").innerHTML=`<tr><th></th><th>${a.n}</th><th>${b.n}</th></tr>`+rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1](a)}</td><td>${r[1](b)}</td></tr>`).join("")}
function nut(){const q=$("#q").value.toLowerCase(),cats=["All",...new Set(F.map(f=>f.c))];
$("#cats").innerHTML=cats.map(c=>`<button data-c="${c}" aria-pressed="${c==cat}">${c}</button>`).join("");
$("#foods").innerHTML=F.map((f,i)=>({f,i})).filter(o=>(cat=="All"||o.f.c==cat)&&o.f.n.toLowerCase().includes(q)).map(({f,i})=>{const bad=f.tg.some(t=>cur.intol.includes(t));return `<tr><td>${f.n}</td><td>${f.k}</td><td>${f.p}</td><td>${f.fe}</td><td>${bad?'<span class="st ct">Constraint identified: conflicts with '+cur.diet+" ("+cur.intol.join(", ")+"). Alternative: "+F[f.alt].n+" ("+F[f.alt].k+" kcal*, "+F[f.alt].p+" g protein* vs "+f.k+"/"+f.p+"). Iron and amino-acid data unavailable, so not claimed equivalent.</span>":f.t}</td><td><button data-a="${i}" aria-label="Add ${f.n} to meal plan">Add</button></td></tr>`}).join("");
if(!$("#foods").innerHTML)$("#foods").innerHTML='<tr><td colspan="6">No foods match this search or category.</td></tr>';const items=Object.entries(meal),k=items.reduce((s,[i,n])=>s+F[i].k*n,0),p=items.reduce((s,[i,n])=>s+F[i].p*n,0);
$("#plan").innerHTML=items.length?items.map(([i,n])=>`<div>${F[i].n} ×${n} <button data-r="${i}" aria-label="Remove ${F[i].n}">Remove</button></div>`).join("")+`<p><b>${k} kcal*, ${p} g protein*</b> <span class="tag f">Placeholder values</span></p>`+(items.some(([i])=>F[i].tg.some(t=>cur.intol.includes(t)))?`<p class="st rv">Review required: plan includes a restricted item. Suggested alternative: Rehydratable lentil soup (similar protein role; iron data unavailable).</p>`:""):"Nothing added yet."}
function assessList(){const a=cur,d=+$("#dur").value,t=$("#mt").value,s=$("#sun").value,eva=t=="eva",L=[],mp=Object.keys(meal).map(i=>F[i]),bad=mp.some(f=>f.tg.some(x=>cur.intol.includes(x)));
const r=(st,ti,tx,wy,rf)=>L.push([st,ti,tx,wy,rf||[]]);
r(a.rep[0]<6||a.fat>=4||a.st>=4?"rv":"ok","Sleep and fatigue",`Reported ${a.rep[0]} h sleep, ${a.rep[1]} interruptions; fatigue ${lv(a.fat)}, stress ${lv(a.st)} (self-reported).`,"Rule S1 (illustrative): sleep under 6 h, or fatigue/stress 4+ of 5, flags a review before assignment. The threshold is a prototype choice, not a NASA limit."+(eva&&d>=6&&a.rep[0]<6?" Rule S2: it matters more for a long EVA ("+d+" h).":""));
r("ok","Health observations",`Simulated vitals available; soreness: ${a.sore}.`,"Rule H1: vitals are shown, not judged. Ordinary reference ranges are not mission thresholds, and no diagnosis is inferred from one reading.");
r(a.hyd!="Good"||(eva&&d>=6)||bad?"rv":"ok","Nutrition and hydration",`Hydration ${a.hyd}; ${mp.length?mp.length+" food item(s) planned"+(bad?", one conflicts with the dietary profile":""):"no meal plan built yet"}.`,"Rule N1 (illustrative): fair/poor hydration, a restricted food in the plan, or an EVA of 6 h or more asks for a fluid and food review. EVA fluid needs are not sourced here.");
r("ok","Cabin requirements","Cabin is at 101.3 kPa, about 21% O2 (ISS nominal). CO2, radiation and noise limits: data unavailable.","Rule C1: cabin values come from the Cabin view; unsourced ones stay unavailable.",[5]);
r(eva?"ct":"ok","Spacesuit requirements",eva?`EMU-style suit: 29.6 kPa, 100% O2, water cooling. Plan ${d} h against a design target of up to 8 h (secondary source).`:"Not required for this task.",eva?"Rule E1: EVA requires the suit panel checks; pressure is far below cabin pressure, so oxygen prebreathe is part of preparation. "+(d>=7?"Rule E2 (illustrative): 7 h or more leaves little margin against the 8 h target.":"Duration is within the 8 h target."):"Rule E0: suit checks apply to EVA only.",eva?[2,3,6]:[]);
r(eva?"ct":"na","External hazards",eva?(s=="sun"?"Sunlit exposure: confirm suit thermal-management checks. Radiation: data unavailable.":"Shadow exposure: confirm cold exposure and cooling settings. Radiation: data unavailable."):"Not assessed for non-EVA tasks.",eva?"Rule X1: temperature extremes are a stated reason suits exist, and the LCVG water loop manages body heat. No external temperature value is sourced, so none is shown.":"Rule X0: external hazards apply to EVA only.",eva?[1,2]:[]);
const need={eva:"spacewalk",exp:"experiment",mnt:"repair"},m=a.sk.concat(a.r).join(" ").toLowerCase().includes(need[t])||(t=="eva"&&a.ev>=3)||(t=="mnt"&&/engineer|maintenance|electronics/i.test(a.sk.concat(a.r).join(" ")));
r(m?"ok":"rv","Skills",m?"Skills or experience align with the task.":"Limited matching skills or EVA history; consider pairing or briefing.","Rule K1: task keywords are compared with fictional skills and EVA history.");
r("na","Information gaps","Radiation, CO2 limits, noise, humidity, external temperatures, EVA nutrient needs: data unavailable.","Rule G1: missing data is shown, not filled in.");return L}
function assess(){$("#dv").textContent=$("#dur").value;const T={ok:"Information available",rv:"Review required",ct:"Constraint identified",na:"Data unavailable"},L=assessList();
const ln=[];if(L[0][0]=="rv")ln.push("Sleep and fatigue → Skills and task duration (S1, S2)");if(L[2][0]=="rv")ln.push("Hydration and meal plan → suit consumables for "+$("#dur").value+" h (N1)");if($("#mt").value=="eva")ln.push("Cabin 101.3 kPa → suit 29.6 kPa → prebreathe (C1, E1) → thermal checks for exposure (X1)");
$("#assess").innerHTML=L.map(x=>`<div class="card"><h3>${x[1]}</h3><div class="st ${x[0]}">${T[x[0]]}</div><p>${x[2]}</p><p class="u">${x[3]} ${cite(x[4])}</p></div>`).join("")+`<div class="card" style="grid-column:1/-1"><h3>How the factors connect</h3><p>${ln.length?ln.join("<br>"):"No cross-links triggered for this setup."}</p></div><div class="note" style="grid-column:1/-1"><b>Not a decision:</b> rules S/H/N/C/E/X/K/G are illustrative prototype logic. There is no score, no go/no-go and no NASA or medical validation.</div>`}
$("#who").innerHTML=A.map(a=>`<option value="${a.id}">${a.n}</option>`).join("");
$("#who").onchange=e=>{cur=A.find(a=>a.id==e.target.value);meal={};render()};
document.addEventListener("click",e=>{const b=e.target.closest("[data-id],[data-e],[data-c],[data-a],[data-r],[data-p],circle");if(!b)return;const d=b.dataset;
if(d.id){cur=A.find(a=>a.id==d.id);$("#who").value=d.id;meal={};render()}
else if(d.p!=null){suitSel(+d.p)}else if(d.e){const x=ENV[envm][d.e];$("#envx").innerHTML=`<h3>${x[0]}</h3><p>${x[3]}</p><p class="u">Value basis: ${x[2]}</p>`}
else if(d.c){cat=d.c;nut()}else if(d.a){meal[d.a]=(meal[d.a]||0)+1;nut()}else if(d.r){delete meal[d.r];nut()}
else if(d.i!=null){const i=+d.i;$("#hrread").textContent="Day "+(i+1)+": "+cur.hr[i]+" bpm (simulated)"}});
$("#vsum").onclick=()=>{view="sum";$("#vsum").setAttribute("aria-pressed",true);$("#vdet").setAttribute("aria-pressed",false);render()};
$("#vdet").onclick=()=>{view="det";$("#vdet").setAttribute("aria-pressed",true);$("#vsum").setAttribute("aria-pressed",false);render()};
$("#tc").onclick=()=>{envm="cabin";$("#tc").setAttribute("aria-pressed",true);$("#ts").setAttribute("aria-pressed",false);envr()};
$("#ts").onclick=()=>{envm="suit";$("#ts").setAttribute("aria-pressed",true);$("#tc").setAttribute("aria-pressed",false);envr()};
$("#q").oninput=nut;["#mt","#dur","#sun"].forEach(s=>$(s).oninput=assess);
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)$$("nav a").forEach(a=>a.classList.toggle("on",a.getAttribute("href")=="#"+e.target.id))}),{rootMargin:"-40% 0px -55% 0px"});$$("section").forEach(s=>io.observe(s));
const cv=$("#stars"),cx=cv.getContext("2d");let S=[];function rs(){cv.width=innerWidth;cv.height=innerHeight;S=Array.from({length:140},()=>({x:Math.random()*cv.width,y:Math.random()*cv.height,r:Math.random()*1.4+.2,s:Math.random()*.15+.02}))}
function dr(){cx.clearRect(0,0,cv.width,cv.height);cx.fillStyle="#dfe9ff";S.forEach(s=>{cx.globalAlpha=.4+s.r/3;cx.beginPath();cx.arc(s.x,s.y,s.r,0,7);cx.fill();if(!matchMedia("(prefers-reduced-motion:reduce)").matches){s.y+=s.s;if(s.y>cv.height)s.y=0}});if(!matchMedia("(prefers-reduced-motion:reduce)").matches)raf=requestAnimationFrame(dr)}
let raf;rs();addEventListener("resize",rs);addEventListener("pagehide",()=>cancelAnimationFrame(raf));dr();suitInit();cmpInit();refInit();render();